### ISSUE TITLE
Fails with TypeError: Cannot read property 'initializeJSI' of null, js engine: hermes

### ISSUE THREAD

**Issue by theianjohnson** [morrowdigital/watermelondb-plugin-example#1]
Steps to reproduce
1. `git clone git@github.com:morrowdigital/watermelondb-plugin-example.git`
2. `cd watermelondb-plugin-example`
3. `npm install`
4. `npx expo start`

Result
```
 ERROR  TypeError: Cannot read property 'initializeJSI' of null, js engine: hermes
 ERROR  Invariant Violation: "main" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called., js engine: hermes
```

**Comment by agutierrezgit** [comment]
I haven't checked this particular example myself but to run watermelondb with expo I needed a [Development Build](https://docs.expo.dev/develop/development-builds/introduction/)

**Comment by killerchip** [comment]
Hello @theianjohnson . Indeed this needs a dev-client in order to work.
If instead of `npx expo start` you run `npx expo run:ios` or `npx expo run:android`, being in SDK 49 now, it will automatically build and install one.

**Comment by killerchip** [comment]
Closing this by default
