### ISSUE TITLE
no such module 'ExpoModulesCore'

### ISSUE THREAD

**Issue by theianjohnson** [morrowdigital/watermelondb-plugin-example#3]
I started with a fresh `git clone ...`, `npm install`, and `npx expo run:ios` (in the readme you also have `npx expo start:ios` - is that a typo?) and this is the output. What am I missing?

<img width="1308" alt="image" src="https://github.com/morrowdigital/watermelondb-plugin-example/assets/4634364/6c138307-344a-40fb-b118-46e7b4fe8b87">

**Comment by theianjohnson** [comment]
I did get https://github.com/skam22/watermelondb-expo-plugin to work if that helps pinpoint any issues

**Comment by killerchip** [comment]
Thank you for your feedback.

Can you check if your path has any spaces?: According to this?
https://github.com/facebook/react-native/issues/37559

Do you use M1 architecture?

**Comment by rawestmoreland** [comment]
There's a PR open with a patch for this issue https://github.com/morrowdigital/watermelondb-expo-plugin/pull/24

**Comment by killerchip** [comment]
Closing this, as it was dealt with on v2.3.1 of the config plugin.
See here:
https://github.com/morrowdigital/watermelondb-expo-plugin/issues/34
